#!/usr/bin/env bash

DB_NAME=$1
DB_USER=$2
DB_PASS=$3

PSQL_CMD="psql -U admin -h fred-postgres -d postgres"

$PSQL_CMD -c "\du" | grep "$DB_USER" || $PSQL_CMD -c "CREATE ROLE $DB_USER NOSUPERUSER LOGIN PASSWORD '$DB_PASS'"
$PSQL_CMD -c "\l" | grep -q $DB_NAME || $PSQL_CMD -c "CREATE DATABASE $DB_NAME OWNER=$DB_USER"
$PSQL_CMD -c "REVOKE ALL ON DATABASE $DB_NAME FROM PUBLIC"
$PSQL_CMD -c "GRANT CONNECT ON DATABASE $DB_NAME TO $DB_USER"