
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:511.0.0-alpine

ARG KASTCTL_VERSION=2.18.0
ARG TERRAFORM_VERSION=1.10.5
ARG KAST_REPO_USER=${KAST_REPO_USER}
ARG KAST_REPO_PASSWORD=${KAST_REPO_PASSWORD}

ENV PATH="${PATH}:/google-cloud-sdk/bin"

RUN apk update && \
    apk add --no-cache curl envsubst helm jq openssh-client python3 wget

# Google Cloud Platform
RUN gcloud components install kubectl

# Install Kastctl
RUN wget --user ${KAST_REPO_USER} --password ${KAST_REPO_PASSWORD} https://artifactory.thalesdigital.io/artifactory/generic-internal/kast/packages/edge/kastctl_amd64-${KASTCTL_VERSION}.tar.gz && \
    tar -xvf kastctl_amd64-${KASTCTL_VERSION}.tar.gz && \
    mv kastctl /usr/local/bin/ && \
    chmod +x /usr/local/bin/kastctl

# Install Terraform
RUN mkdir /tmp/tf && \
    curl -s https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o /tmp/tf/terraform.zip && \
    unzip /tmp/tf/terraform.zip -d /tmp/tf && \
    mv /tmp/tf/terraform /usr/local/bin/terraform && \
    rm -rf /tmp/tf

# Install TFLint
RUN curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

ENTRYPOINT ["/bin/sh", "-c"]