# -----------------------------------------------------------------------------
# BUILDER
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/node:22.13.0 AS builder

# Install dependencies
RUN apt-get update && \
    apt-get install -y make

# Copy project files
COPY .. /app

# Move to project directory
WORKDIR /app

# Build web app
RUN make build

# -----------------------------------------------------------------------------
# RUNTIME
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/nginx:1.27.3-alpine AS runtime

# Copy web app from builder to nginx html directory
COPY --from=builder --chown=nginx:nginx /app/dist /usr/share/nginx/html

# Set permissions to nginx html directory
RUN chown -R nginx: /usr/share/nginx/html

# Expose default nginx port
EXPOSE 80

# Execute nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]